### ISSUE TITLE
Does not work together with cordova-plugin-sfauthenticationsession using Cordova iOS 5.0.1

### ISSUE THREAD

**Issue by RasimKanca** [mochini/cordova-plugin-aswebauthenticationsession#1]
I have been using the `cordova-plugin-aswebauthenticationsession` and `cordova-plugin-sfauthenticationsession` plugins side by side to be able to support iOS 11 and up. This worked fine until I updated Cordova to 9.0.0 and started using Cordova iOS 5.0.1. Now when I build my app, I get the following error: 
```
duplicate symbol __authenticationVC in:
    .../Objects-normal/arm64/ASWebAuthSession.o
   .../Objects-normal/arm64/SFAuthSession.o
ld: 1 duplicate symbol for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I tested this both locally using Xcode 10.3 and on PhoneGap Build. The issue seems pretty clear, although I am not sure why this error only started appearing after the update to Cordova iOS 5.0.1. If I build with Cordova iOS 4.5.4 for example, these plugins work side by side without any issues.

Renaming the symbol solves the problem. I will open a pull request to do that, but I am also curious whether it would be interesting to also support iOS 11 in this plugin.

**Comment by petergrau** [comment]
@RasimKanca did you open the PR in this repo?

**Comment by RasimKanca** [comment]
> @RasimKanca did you open the PR in this repo?

Yep.
